---
title: "stat-345-midterm-code"
author: "Isaac Dhyanchand"
date: "2025-11-04"
output: html_document
---
```{r}
# Importing libraries for use
library(ggplot2)
library(gganimate)
library(tidyverse)
library(devtools)
library(nbastatR)
library(extrafont)
library(cowplot)
library(scales)
```


```{r}
# Creating court and plotting (From DomSamangy on GitHub)

circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}

# Court Dimensions & lines
width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 16
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14

# Court themes
court_themes = list(
  light = list(
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"
  ),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"
  ),
  ppt = list(
    court = 'gray20',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray20"
)
)

# Function to create court based on given dimensions
# Inputs: court theme, three point length
# Output: Graph with basketball court on it

plot_court = function(court_theme = court_themes$light, use_short_three = FALSE) {
  if (use_short_three) {
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = data_frame(
    x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
    y = c(height, 0, 0, height, height),
    desc = "perimeter"
  )
  
  court_points = bind_rows(court_points , data_frame(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(0, key_height, key_height, 0),
    desc = "outer_key"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = "backboard"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(0, 0), y = c(backboard_offset, backboard_offset + neck_length), desc = "neck"
  ))
  
  foul_circle = circle_points(center = c(0, key_height), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0("foul_circle_bottom_", angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = data_frame(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = "three_point_line"
  )
  
  court_points = bind_rows(
    court_points,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  court_points <- court_points
  
  # Final plot creation
  ggplot() +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines
    ) +
    coord_fixed(ylim = c(0, 45), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(
      text = element_text(color = court_theme$text),
      plot.background = element_rect(fill = 'gray20', color = 'gray20'),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
      legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.text = element_text(size = rel(1.0))
    )
}

``` 
    
```{r, result=FALSE}
# Needed to increase to run team_shots() function 
Sys.setenv("VROOM_CONNECTION_SIZE" = 5e6) 

# Grab team shot data
bulls_2024 <- teams_shots(teams = "Chicago Bulls", seasons = 2024, season_types = "Regular Season")

bulls_2023 <- teams_shots(teams = "Chicago Bulls", seasons = 2023, season_types = "Regular Season")

bulls_2022 <- teams_shots(teams = "Chicago Bulls", seasons = 2022, season_types = "Regular Season")

bulls_2021 <- teams_shots(teams = "Chicago Bulls", seasons = 2021, season_types = "Regular Season")

bulls_2020 <- teams_shots(teams = "Chicago Bulls", seasons = 2020, season_types = "Regular Season")

bulls_2019 <- teams_shots(teams = "Chicago Bulls", seasons = 2019, season_types = "Regular Season")

bulls_2018 <- teams_shots(teams = "Chicago Bulls", seasons = 2018, season_types = "Regular Season")

bulls_2017 <- teams_shots(teams = "Chicago Bulls", seasons = 2017, season_types = "Regular Season")

bulls_2016 <- teams_shots(teams = "Chicago Bulls", seasons = 2016, season_types = "Regular Season")

bulls_2015 <- teams_shots(teams = "Chicago Bulls", seasons = 2015, season_types = "Regular Season")

bulls_2014 <- teams_shots(teams = "Chicago Bulls", seasons = 2014, season_types = "Regular Season")

# Bind the rows together
bulls <- bind_rows(
  '2014' = bulls_2014,
  '2015' = bulls_2015,
  '2016' = bulls_2016,
  '2018' = bulls_2018,
  '2019' = bulls_2019,
  '2020' = bulls_2020,
  '2021' = bulls_2021,
  '2022' = bulls_2022,
  '2023' = bulls_2023,
  '2024' = bulls_2024,
  .id = "season"
)
# Filter shot data for player & clean data to fit court dimensions
bulls <- bulls %>% 
  mutate(x = as.numeric(as.character(locationX)) / -10, y = as.numeric(as.character(locationY)) / 10 + hoop_center_y)

```
```{r}
# Plotting our points onto court (From DomSamangy on Github)

p1 <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = bulls, aes(x = x, y = y, 
             color = isShotMade, fill = isShotMade), 
             size =3, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("green4","red3"), 
                     aesthetics = "color", 
                     breaks=c("TRUE", "FALSE"), 
                     labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"), 
                    aesthetics = "fill", 
                    breaks=c("TRUE", "FALSE"), 
                    labels=c("Made", "Missed")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) +
  scale_y_continuous(limits = c(0, 45)) +
  theme(plot.title = element_text(hjust = .5, size = 22, 
                                  family = "Comic Sans MS", 
                                  face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, 
                                     family = "Comic Sans MS", 
                                     face = "bold", vjust = -8),
        legend.position = c(.5, .85),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, 
                                   family = "Comic Sans MS", 
                                   face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, 
                                    family = "Comic Sans MS", 
                                    face = "bold", colour = "lightgrey", 
                                    vjust = 8)) +
  labs(caption = "Tutorial: @DSamangy") + 
  labs(title = "Chicago Bulls Shots - Season: {current_frame}") +
  transition_manual(season) + # Used transition_manual instead of transition_states to control speed better
  enter_fade() + exit_fade() + 
  theme(plot.background = element_rect(fill="gray20", color = NA),
          plot.caption = element_text(size = 14)) 

# Animate seasons in a row, adjusted parameters to tolerable speed
anim <- animate(p1, fps = 8, duration = 20, width = 800, height = 700)
print(anim)  

# Saving the gif
#anim_save("bulls_shots.gif", animation = anim)

```
```{r}
# Grouping shots by region so we can get shot percentages from each region

# Zone % by season
zone_by_season <- bulls %>%
  group_by(season, zoneBasic) %>%
  summarise(attempts = n(),
            makes = sum(isShotMade, na.rm = TRUE),
            fg_pct = makes / attempts ) %>%
  arrange(season, zoneBasic)

```

```{r}
# Naming the points of my zones and locations for visual
zone_centers <- tibble(
  zoneBasic = c("Restricted Area","In The Paint (Non-RA)",
                "Mid-Range","Above the Break 3",
                "Left Corner 3","Right Corner 3"),
  x = c(0,0 ,0 ,0 ,-22.5,22.5),
  y = c(4,12,22,31,    6,   6)
)

# Picking the last 3 seasons and build plot data
last3 <- tail(sort(unique(zone_by_season$season)), 3)
plot_dat_last3 <- zone_by_season %>%
  filter(season %in% last3) %>%
  mutate(fg = fg_pct, 
         lbl = percent(fg, 0.1)) %>%
  left_join(zone_centers, by = "zoneBasic") # Left_join because we want to keep all values in "zone_by_season"

# Plotting points for zones
plot_court(court_themes$ppt) +
  geom_point(data = plot_dat_last3, 
             
# size = attempts and fill = fg for our visualization
             aes(x, y, size = attempts, fill = fg), 
             shape = 21, color = "gray20", alpha = 0.95, stroke = 0.4) +
# Labels for each zone
  geom_text(data = plot_dat_last3, 
            aes(x, y, label = lbl),
            vjust = -1.1, size = 3, 
            color = "white", fontface = "bold") +
# Used guide = "none" to void legend for size (bigger = more is general idea)
  scale_size_area(max_size = 12, guide = "none") +
# Building the legend for %'s (Diverse color scheme)
  scale_fill_viridis_c(option = "C", end = 0.95, 
                       limits = c(0, 0.70),  #Percentages don't get higher than 70%.
                       labels = percent_format(1), 
                       name = "FG%") +
# Facet by season for 3 graphs
  facet_wrap(~ season, ncol = 3) +  
  labs(title = "Bulls Zone Efficiency (last three seasons)") +
  theme_void(base_size = 11) +

# Adjusting the theme to dark and setting the text to white
  theme(plot.background = element_rect(fill = "gray20", color = NA),
        plot.title = element_text(hjust = 0.5, color = "white"),
        strip.text = element_text(color = "white", face = "bold")) + 
# Added to fix legend positioning and size  
  guides(fill = guide_colorbar( 
      title.position = "top",
      barwidth = 0.6, barheight = 7, ticks = FALSE,
      title.theme = element_text(color = "white"),
      label.theme = element_text(color = "white")
    )
  )
```

```{r}
# Putting our wanted values into a separate table
zone_table <- zone_by_season %>%
  mutate(fg_pct = round(fg_pct , 3)) %>%   
  select(season, zoneBasic, fg_pct)

# Heatmap that shows percentages from all different zones from 2014-2024
ggplot(zone_table, aes(season, zoneBasic, 
                       fill = fg_pct)) +
  geom_tile(color = "gray15") +
  geom_text(aes(label = fg_pct), size = 2.5) +
  scale_fill_viridis_c(option = "C", end = 0.95, 
                       limits = c(0, 0.70), 
                       labels = percent_format(accuracy = 1)) +
  labs(x = "Season", y= "Zone", fill = "FG%") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid = element_blank())

```

```{r}
# Arrange our data for line graph
plot_dat <- zone_by_season %>%
  arrange(season) %>%
  mutate(season = factor(season, levels = unique(season)))

# Line graph showing attempts over last 10 years
ggplot(plot_dat, aes(season, attempts, 
                     color = zoneBasic, 
                     group = zoneBasic)) +
  geom_line(linewidth = 1) +
  geom_point(size = 1.9) +
  scale_color_viridis_d(option = "C", end = 0.95, name = "Zone") + 
  labs(x = "Season", y = "Attempts") +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # X label adjustments

```


